/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package merit.calculator;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author jesper.rudegran
 */
public class CalculatorGUI extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        courseLabel = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        addCourseBtn = new javax.swing.JButton();
        deleteCourseBtn = new javax.swing.JButton();
        extraMeritLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        meritOutput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        courseInputField = new javax.swing.JTextField();
        pointsBox = new javax.swing.JComboBox<>();
        gradeBox = new javax.swing.JComboBox<>();
        extraMeritBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveMenuBtn = new javax.swing.JMenuItem();
        loadMenuBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        titleLabel.setBackground(new java.awt.Color(204, 204, 204));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 204, 204));
        titleLabel.setText("Merit-Calculator");

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(51, 51, 51));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        textArea.setFocusable(false);
        textArea.setSelectionColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(textArea);

        courseLabel.setBackground(new java.awt.Color(204, 204, 204));
        courseLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        courseLabel.setForeground(new java.awt.Color(204, 204, 204));
        courseLabel.setText("Course:");

        pointsLabel.setBackground(new java.awt.Color(204, 204, 204));
        pointsLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pointsLabel.setForeground(new java.awt.Color(204, 204, 204));
        pointsLabel.setText("Points:");

        gradeLabel.setBackground(new java.awt.Color(204, 204, 204));
        gradeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(204, 204, 204));
        gradeLabel.setText("Grade:");

        addCourseBtn.setText("Add course");
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });

        deleteCourseBtn.setText("Delete course");
        deleteCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseBtnActionPerformed(evt);
            }
        });

        extraMeritLabel.setBackground(new java.awt.Color(204, 204, 204));
        extraMeritLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        extraMeritLabel.setForeground(new java.awt.Color(204, 204, 204));
        extraMeritLabel.setText("Extra merit:");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Your merit:");

        meritOutput.setEditable(false);
        meritOutput.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        meritOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        meritOutput.setFocusable(false);

        courseInputField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pointsBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pointsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50", "100", "150", "200" }));

        gradeBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gradeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "-" }));

        extraMeritBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        extraMeritBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "0.5", "1", "1.5", "2" }));

        jButton1.setText("Delete all");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleLabel)
                        .addGap(224, 224, 224))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(meritOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(courseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(courseInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(extraMeritLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(extraMeritBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gradeLabel)
                                        .addComponent(pointsLabel))
                                    .addGap(67, 67, 67)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gradeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pointsBox, 0, 83, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseLabel)
                            .addComponent(courseInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointsLabel)
                            .addComponent(pointsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gradeLabel)
                            .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extraMeritLabel)
                            .addComponent(extraMeritBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(meritOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        saveMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveMenuBtn.setText("Save");
        saveMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuBtn);

        loadMenuBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loadMenuBtn.setText("Load");
        loadMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(loadMenuBtn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Student student;
    String merit = "0";
    
    private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed
      
      String courseName = courseInputField.getText();
      int coursePoints = Integer.parseInt(pointsBox.getSelectedItem().toString());
      String courseGrade = gradeBox.getSelectedItem().toString();
      double courseExtraMerit = Double.parseDouble(extraMeritBox.getSelectedItem().toString());
      
      if("".equals(courseName) || "please enter a course name".equals(courseName)){
          courseInputField.setText("please enter a course name");
      }else{
          student.courses.add(new Course(courseName, coursePoints, courseGrade, courseExtraMerit));
          updateGUI();
      }
    }//GEN-LAST:event_addCourseBtnActionPerformed
   
    MeritCalculator calculator = new MeritCalculator();
    public void updateGUI(){
      String strCourses = "";
      
      for (Course course : student.courses) {
          strCourses += course.getCourseInformation() + "\n";
      }
      
      textArea.setText("""
                       Course | Points | Grade | Extra merit
                       _____________________________________________
                       
                       """+ strCourses);
      merit = calculator.calculateMerit(student.courses);
      
      if(String.valueOf(merit).equals("NaN")){
          meritOutput.setText("0");
          
      } else {
          meritOutput.setText(merit);
      } 
    }
    
    private void deleteCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseBtnActionPerformed
        String deleteCourseIndex = JOptionPane.showInputDialog("Enter course index (only number(s))", "1-n");
        try{
            student.courses.remove(Integer.parseInt(deleteCourseIndex)-1);
            updateGUI();
        } catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(rootPane,"Course number is out of bounds.");
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane,"Please only enter numbers.");
        }
    }//GEN-LAST:event_deleteCourseBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        student.courses.removeAll(student.courses);
        updateGUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuBtnActionPerformed
        try {
            loadObject();
        } catch (IOException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadMenuBtnActionPerformed

    private void saveMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuBtnActionPerformed
        try {
            writeObject();
        } catch (IOException ex) {
            Logger.getLogger(CalculatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveMenuBtnActionPerformed
    
    //skriver kurser till fil
    public void writeObject() throws IOException{
        FileOutputStream fos = new FileOutputStream(student.encSSN + ".dat");
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeObject(student.courses);
        System.out.println("finished");
        oos.close();
        fos.close();
    }
    
    //laddar kurser från fil
    public void loadObject () throws FileNotFoundException, IOException, ClassNotFoundException{
        FileInputStream fis = new FileInputStream(student.encSSN +".dat");
        ObjectInputStream ois = new ObjectInputStream(fis);
        
        student.courses = (ArrayList<Course>) ois.readObject();
        updateGUI();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addCourseBtn;
    public javax.swing.JTextField courseInputField;
    public javax.swing.JLabel courseLabel;
    public javax.swing.JButton deleteCourseBtn;
    public javax.swing.JComboBox<String> extraMeritBox;
    public javax.swing.JLabel extraMeritLabel;
    public javax.swing.JComboBox<String> gradeBox;
    public javax.swing.JLabel gradeLabel;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JMenuItem loadMenuBtn;
    public javax.swing.JTextField meritOutput;
    public javax.swing.JComboBox<String> pointsBox;
    public javax.swing.JLabel pointsLabel;
    public javax.swing.JMenuItem saveMenuBtn;
    public javax.swing.JTextArea textArea;
    public javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
